### ISSUE TITLE
View Upcoming Events List

### ISSUE THREAD

**Issue by nikhen-s** [swent-sp-2024-event-radar/event-radar-app#107]
## Objective
- List all events you are attending in descending order You should see the Event Date, Name and Location  (Future and Passed) Name, location & Date of each event should be displayed 

## Acceptance Criteria

- [ ] This Screen accessible from the default home screen of browsing events (similar to how Jalen presented it on Figma)
- [ ] List all events you are attending in descending order You should see the Event Date, Name and Location  (Future and Passed) Name, location & Date of each event should be displayed 
- [ ] Upon Clicking on Event, screen 2.12 (Event Overview) pops up

**Comment by Nath-Assa** [comment]
Resolved in #184
