### ISSUE TITLE
Create "My Hosting" page: UI/View + Tests

### ISSUE THREAD

**Issue by nikhen-s** [swent-sp-2024-event-radar/event-radar-app#110]
## Link To User Story and Figma
User Story #76, Figma Issue #98 

## Objective
- Implement the UI upon clicking My Hostings in Bottom Navigation Bar

## Acceptance Criteria
- [ ] Contains "+" Button to create new event.
- [ ] If user does not host an event, displays text "No hosted events"
- [ ] Displays events that the user hosts in cards containing the event details. Upon clicking, it leads to event overview.

**Comment by christinehahaa** [comment]
Task was done in sprint 4 (XXX hrs @nikhen-s to update) and is to be finalized in sprint 5.
