### ISSUE TITLE
Update Upcoming events ViewModel for map View (Query the database interface, show approximate location + test)

### ISSUE THREAD

**Issue by nikhen-s** [swent-sp-2024-event-radar/event-radar-app#119]
## Link to User Stories
#16, User flow 4 in Figma

## Related Issues
#68
resolved in PR #184

## Objective
- be able to view the _approximate_ location of all events on a Map
- achieve feature parity with the list view
- If no upcoming event, FAB should still display empy map view

## Acceptance Criteria
- [ ] mimic the backend of #68, but now in the "upcoming events" tab.

**Comment by Nath-Assa** [comment]
Resoled in #184
