### ISSUE TITLE
View Friends list VM

### ISSUE THREAD

**Issue by achillet3** [swent-sp-2024-event-radar/event-radar-app#200]
# Description
Create the View Model for the event interaction summary screen. 

Linked to Figma Flow #102 and User Flow #23 

# Requirements
- [ ] Interact with the Users database
- [ ] Interact with the Events database
- [ ] Functions to get information from either database

In future, you can see past events, click on the past event and see all the friends you made at that event. For now, implement the contact list on the "messages" page (from the nav bar)

**Comment by jgeaso1266** [comment]
This task will be completed but will be merged with #91 which is still blocked by #182.
