### ISSUE TITLE
Event interaction summary

### ISSUE THREAD

**Issue by achillet3** [swent-sp-2024-event-radar/event-radar-app#23]
# User Story
As an event goer, I want to see a list of people whose QR codes I have scanned in each event and easily recall who I met.
# Acceptance Criteria
- Display a list of users I created a strong (both users scanned each others QR Code)
- The list should be cards with options to see their profile, chat with them, and share pictures directly from your gallery

**Comment by jgeaso1266** [comment]
This user story needs to be edited. The weak interaction is no longer accepted.
