### ISSUE TITLE
Create Events Database

### ISSUE THREAD

**Issue by achillet3** [swent-sp-2024-event-radar/event-radar-app#29]
# Link to User Stories
#15 and #16 

# Objective
Create a section in the README that outlines the structure of the firebase database.

The attributes are:
- Name
- Time
- Date
- Location
- Description
- Photo
- Type of Event
- Ticket Price
- List of UIDs of Co-Organisers
- Users with tickets: QR Codes of users who have tickets to event
- Reference to event chat (in Chat database)

# Required Behaviour
- [ ] A section in the README is added.

**Comment by wisdomseeker2001** [comment]
UID of person creating event needs to be automatically added to list of Co_organisers
