### ISSUE TITLE
Bug fix: Remove past events from browse and upcoming events

### ISSUE THREAD

**Issue by jgeaso1266** [swent-sp-2024-event-radar/event-radar-app#296]
## Objective
- when events have passed, remove them from upcoming and browse events lists
- possibly move to a separate list in firebase to leave the current events unobstructed (decided not to do this, as not a better solution - based on David's advice)

**Comment by christinehahaa** [comment]
There was an issue with removing them from upcoming and hosted events due to having to pass the userId into these VMs. It has been decided that it is not necessary to remove them, as it is okay to view past upcoming and hosted events.
