### ISSUE TITLE
Wireframes + Mockups for User profile setup

### ISSUE THREAD

**Issue by nikhen-s** [swent-sp-2024-event-radar/event-radar-app#31]
Figma Link: https://www.figma.com/file/yCDFrt0sOYFhXlYlWp8sZT/Event-Radar-App?type=design&node-id=0-1&mode=design&t=byPHNODWRIbRIw74-0

Create the Figma Wireframe for Profile Setup: User sets up their profile, including interests and preferences.

User Story: 
As a user, I want to indicate the types of events I'm interested in upon signing up, so that the app can personalize my experience and recommend relevant events to me based on my preferences.

**Comment by Viccha18** [comment]
To me it looks good.
