### ISSUE TITLE
Refine UX and UI aesthetics

### ISSUE THREAD

**Issue by Viccha18** [swent-sp-2024-event-radar/event-radar-app#313]
# Objective
Review the UI and UX, ensure it is good looking, intuitive and in accordance with the figma. Edit Figma accordingly.

_Refine the UX, ensure the interface is intuitive and user-friendly, and put the finishing touches on UI aesthetics._
_Usability: As a beta release, the app need not be pretty and sleek, but the usability needs to be there. Essential UX design elements, like navigation bars, the profile tab, filters, etc. should be ready for prime time. Usability is a fundamental part of the design. Take a look, for instance, at the ChatGPT mobile app: it is simple, and it hides everything in a side navbar, and the main activity is a simple search textbox. This is an intuitive UI. The main user interaction is put into focus, and the number of CTAs (calls to action) needed for a user to get value from the app is kept low._

From : https://github.com/swent-epfl/public/blob/main/project/handouts/m4-deliverables.md

**Comment by christinehahaa** [comment]
Figma has been updated to match the latest app. The app needs some UI changes outlined below:
- Cancel Event pop up needs a "no" or "x" button

The following user flows need to be verified with Figma, as they have not been merged into main yet:
- Log out
- edit personal profile
- create event
- view/edit hosted event
- scan ticket

These are to be completed in 1 PR.

**Comment by christinehahaa** [comment]
Took longer than expected due to a bug in My Hosted making it not scrollable. Instead removed organisers from that page so no scrolling is needed.
