### ISSUE TITLE
Wireframes + Mockups for 8. Scan A QR Code (to add friend)

### ISSUE THREAD

**Issue by Viccha18** [swent-sp-2024-event-radar/event-radar-app#32]
Figma Link: https://www.figma.com/file/yCDFrt0sOYFhXlYlWp8sZT/Event-Radar-App?type=design&node-id=0-1&mode=design&t=byPHNODWRIbRIw74-0

Create the Figma Wireframe for Add friend: User can add a new friend to its friend list by exchange scanning their QR code.

User Story: see #17 
As an event goer, I want to scan the QR codes of people I meet so that I can keep track of who I met and catch up with them later.

Once complete, please tick off the Figma Tracker [here](https://github.com/swent-sp-2024-event-radar/event-radar-app/wiki/Wireframe-Mockup-Completion-Tracker).

**Comment by christinehahaa** [comment]
Follow this workflow: 
1. Check this [file](https://docs.google.com/spreadsheets/d/1qhejj2aUG32Ffew8Si8NhP8Zs_BScI0jVGiMzR-OB-U/edit#gid=0) - each user flow maps to a description in Joyti's blueprint. The user flows and joyti's blueprint are named and numbers so it should be easy to find. 
2. Read the corresponding [blueprint](https://docs.google.com/document/d/1PEt4z2dIuSomhoc1I43wu28xT3m0dsGcAmQ_SnZmLVc/edit) bulletpoint and make sure your wireframe & mockup design matches to what's written in there. 
3. Design the wireframe
4. Design the mockup
5. Get someone(s) to review 
3. Once reviewed and complete, tick it off Jalen's tracker in the wiki, linked [here](https://github.com/swent-sp-2024-event-radar/event-radar-app/wiki/Wireframe-Mockup-Completion-Tracker).
