### ISSUE TITLE
Wireframes + Mockups for 12. Send Message in Private Chat

### ISSUE THREAD

**Issue by christinehahaa** [swent-sp-2024-event-radar/event-radar-app#42]
Figma Link: https://www.figma.com/file/yCDFrt0sOYFhXlYlWp8sZT/Event-Radar-App?type=design&node-id=0-1&mode=design&t=byPHNODWRIbRIw74-0

Create the Figma Wireframe for User initiates or responds to individual chats with other participants.
* User was active x minutes ago

User Story: see https://github.com/swent-sp-2024-event-radar/event-radar-app/issues/20
As a user, I want to be able to chat in-app with everyone of my friends so that it is easy to interact with them (and possibly leverage the information of the app such as links to events)
As a user, I want to be able to access my chat history downloaded on my phone so that I can access it offline

**Comment by christinehahaa** [comment]
Follow this workflow: 
1. Check this [file](https://docs.google.com/spreadsheets/d/1qhejj2aUG32Ffew8Si8NhP8Zs_BScI0jVGiMzR-OB-U/edit#gid=0) - each user flow maps to a description in Joyti's blueprint. The user flows and joyti's blueprint are named and numbers so it should be easy to find. 
2. Read the corresponding [blueprint](https://docs.google.com/document/d/1PEt4z2dIuSomhoc1I43wu28xT3m0dsGcAmQ_SnZmLVc/edit) bulletpoint and make sure your wireframe & mockup design matches to what's written in there. 
3. Design the wireframe
4. Design the mockup
5. Get someone(s) to review 
3. Once reviewed and complete, tick it off Jalen's tracker in the wiki, linked [here](https://github.com/swent-sp-2024-event-radar/event-radar-app/wiki/Wireframe-Mockup-Completion-Tracker).

**Comment by jgeaso1266** [comment]
I believe this is already complete (correct me if I'm wrong).
