### ISSUE TITLE
Create search bar and filter button: UI

### ISSUE THREAD

**Issue by jgeaso1266** [swent-sp-2024-event-radar/event-radar-app#74]
## Link to User Stories
#15, #16, In Figma user flows 3, 4

## Objective
Create a search bar and filter button/pop-up to filter the list on the browse/upcoming events screen on both map and list

## Acceptance Criteria
- [ ] Create a search bar and filter button/pop-up in the UI

**Comment by christinehahaa** [comment]
Task was done in sprint 4 (3hrs) and is to be finalized in sprint 5.
