### ISSUE TITLE
Create search bar and filter button: Backend

### ISSUE THREAD

**Issue by nikhen-s** [swent-sp-2024-event-radar/event-radar-app#88]
## Objective
Create a search bar and filter button/pop-up to filter the list on the browse/upcoming events screen on both map and list

## Acceptance Criteria
- [ ] In the backend, filter the list based on the search bar criteria (which would filter by name) or the filter button (which would filter by distance, category, etc.). (examples in VCS)
- [ ] Create tests for searching and filtering function

**Comment by christinehahaa** [comment]
Started in Sprint 5 (1hr) and finishing in sprint 6
