### ISSUE TITLE
Bug Fix: Google authentication (not allowing Sign In unless the user's personal SHA key is stored)

### ISSUE THREAD

**Issue by christinehahaa** [swent-sp-2024-event-radar/event-radar-app#90]
Fix bug identified from Milestone 1 with Google authentication (not allowing signin unless the user's personal SHA key is stored)

**Comment by jgeaso1266** [comment]
Is this still a bug? I think the coaches said this is expected behavior. The fix is for everyone to add their SHA's to Firestore.
