### ISSUE TITLE
Landing page for messages list

### ISSUE THREAD

**Issue by christinehahaa** [swent-sp-2024-event-radar/event-radar-app#91]
## Link to User Stories
#18 and #20, User flow X in Figma

## Related Issues
#68

## Objective
* be able to view a list of all messages, both from groups and private messages
* This tutorial might be useful: https://youtube.com/playlist?list=PLzLFqCABnRQftQQETzoVMuteXzNiXmnj8&si=xPWdNFXROiDJ5pNk

## Acceptance Criteria
As per the [blueprint](https://docs.google.com/document/d/1PEt4z2dIuSomhoc1I43wu28xT3m0dsGcAmQ_SnZmLVc/edit): **2.2 : Messages Listed**
- [ ] Default message screen shouldList all chats and should pop up upon pressing an icon/ button available on Home Screen  
- [ ] You should have all the chats previously started in chronological order as you scroll down  
- [ ] If you click on one of the private chats it opens the private chat screen (2.21)   
- [ ] From this screen you should be able to go to contacts (2.22)

**Comment by jgeaso1266** [comment]
blocked by #154
